In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

y = df_train["Purchase"]

df_train.drop(["Purchase"],axis=1,inplace=True)

df = pd.concat([df_train,df_test]).iloc[:, 2:]

In [3]:
df.head(10)

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,F,0-17,10,A,2,0,3,NaN,NaN
1,F,0-17,10,A,2,0,1,6.0,14.0
2,F,0-17,10,A,2,0,12,NaN,NaN
3,F,0-17,10,A,2,0,12,14.0,NaN
4,M,55+,16,C,4+,0,8,NaN,NaN
5,M,26-35,15,A,3,0,1,2.0,NaN
6,M,46-50,7,B,2,1,1,8.0,17.0
7,M,46-50,7,B,2,1,1,15.0,NaN
8,M,46-50,7,B,2,1,1,16.0,NaN
9,M,26-35,20,A,1,1,8,NaN,NaN

In [4]:
df.isna().sum()

Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            245982
Product_Category_3            545809
dtype: int64

In [5]:
df = df.fillna(0)

In [6]:
for i in df.columns:
    print(i+":",df[i].unique())

Gender: ['F' 'M']
Age: ['0-17' '55+' '26-35' '46-50' '51-55' '36-45' '18-25']
Occupation: [10 16 15  7 20  9  1 12 17  0  3  4 11  8 19  2 18  5 14 13  6]
City_Category: ['A' 'C' 'B']
Stay_In_Current_City_Years: ['2' '4+' '3' '1' '0']
Marital_Status: [0 1]
Product_Category_1: [ 3  1 12  8  5  4  2  6 14 11 13 15  7 16 18 10 17  9 20 19]
Product_Category_2: [ 0.  6. 14.  2.  8. 15. 16. 11.  5.  3.  4. 12.  9. 10. 17. 13.  7. 18.]
Product_Category_3: [ 0. 14. 17.  5.  4. 16. 15.  8.  9. 13.  6. 12.  3. 18. 11. 10.]

In [7]:
from sklearn.preprocessing import LabelEncoder 

le = LabelEncoder()

df[df.columns] = df[df.columns].apply(lambda col: le.fit_transform(col))

In [8]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

df = np.array(ohe.fit_transform(df).toarray(),dtype=np.str)

In [9]:
from sklearn.preprocessing import StandardScaler

st = StandardScaler()
df = st.fit_transform(df)

df = pd.DataFrame(df)

df

,0,1,2,3,4,5,6,7,8,9,...,84,85,86,87,88,89,90,91,92,93
0,1.745599,-1.745599,5.977729,-0.470329,-0.815516,-0.499981,-0.301442,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
1,1.745599,-1.745599,5.977729,-0.470329,-0.815516,-0.499981,-0.301442,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,5.368100,-0.231824,-0.251067,-0.177047,-0.092308
2,1.745599,-1.745599,5.977729,-0.470329,-0.815516,-0.499981,-0.301442,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
3,1.745599,-1.745599,5.977729,-0.470329,-0.815516,-0.499981,-0.301442,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
4,-0.572869,0.572869,-0.167288,-0.470329,-0.815516,-0.499981,-0.301442,-0.274156,4.962622,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783662,1.745599,-1.745599,-0.167288,-0.470329,1.226217,-0.499981,-0.301442,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
783663,1.745599,-1.745599,-0.167288,-0.470329,1.226217,-0.499981,-0.301442,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
783664,1.745599,-1.745599,-0.167288,-0.470329,1.226217,-0.499981,-0.301442,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,7.665082,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
783665,1.745599,-1.745599,-0.167288,-0.470329,-0.815516,-0.499981,3.317389,-0.274156,-0.201506,-0.379928,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308
783666,1.745599,-1.745599,-0.167288,-0.470329,-0.815516,-0.499981,3.317389,-0.274156,-0.201506,2.632079,...,-0.1468,-0.056583,-0.057528,-0.130462,-0.100584,-0.186286,-0.231824,-0.251067,-0.177047,-0.092308

In [10]:
X = df.iloc[:550068]
X_val = df.iloc[550068:]

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3 , random_state=0)

In [11]:
from sklearn.ensemble import RandomForestRegressor

model1 = RandomForestRegressor(random_state=0)

model1.fit(X_train,y_train)

y_pred1 = model1.predict(X_test)

from sklearn.metrics import mean_squared_error
from math import sqrt

print(sqrt(mean_squared_error(y_test,y_pred1)))

3038.189712043257

In [12]:
from xgboost import XGBRegressor

model3 = XGBRegressor()

model3.fit(X_train,y_train)

y_pred3 = model3.predict(X_test)

print(sqrt(mean_squared_error(y_test,y_pred3)))

[19:14:13] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
3045.1113884173565

In [13]:
from sklearn.linear_model import LinearRegression
model4 = LinearRegression()

model4.fit(X_train,y_train)

y_pred4 = model4.predict(X_test)

print(sqrt(mean_squared_error(y_test,y_pred4)))

3015.439763685617

In [11]:
from keras.models import Sequential
from keras.layers import Dense
from keras.regularizers import l2
from sklearn.metrics import mean_squared_error
from math import sqrt

Using TensorFlow backend.
C:\Users\20114\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\20114\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [13]:
model = Sequential()

model.add(Dense(100,input_dim = 94,kernel_initializer = "uniform",
                     kernel_regularizer = l2(0.1) , bias_regularizer = l2(0.1),
                     bias_initializer="zeros",activation="relu"))
model.add(Dense(50,kernel_initializer = "uniform",
                     kernel_regularizer = l2(0.1) , bias_regularizer = l2(0.1),
                     bias_initializer="zeros",activation="relu"))
model.add(Dense(1))

model.compile(optimizer="adam",loss = "mean_squared_error")

model.fit(X_train,y_train,batch_size=10 ,epochs=100)

WARNING:tensorflow:From C:\Users\20114\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Epoch 1/100
385047/385047 [==============================] - 79s 206us/step - loss: 11227050.5400
Epoch 2/100
385047/385047 [==============================] - 70s 181us/step - loss: 8989595.5553
Epoch 3/100
385047/385047 [==============================] - 63s 163us/step - loss: 8791223.2697
Epoch 4/100
385047/385047 [==============================] - 60s 156us/step - loss: 8579445.8083
Epoch 5/100
385047/385047 [==============================] - 60s 156us/step - loss: 8516445.3054
Epoch 6/100
385047/385047 [==============================] - 60s 157us/step - loss: 8484268.5114
Epoch 7/100
385047/385047 [==============================] - 60s 156us/step - loss: 8449953.3624
Epoch 8/100
385047/385047 [==============================] - 60s 157us/step - loss: 8423196.4517
Epoch 9/100
385047/385047 [==============================] - 60s 156us/step - loss: 8393833.1798
Epoch 10/100
385047/385047 [==============================] - 60s 155us/step - loss: 8369081.9983
Epoch 11/100
385047/385047 [==============================] - 59s 154us/step - loss: 8344210.7392
Epoch 12/100
385047/385047 [==============================] - 63s 165us/step - loss: 8318298.6938
Epoch 13/100
385047/385047 [==============================] - 62s 161us/step - loss: 8294083.9431
Epoch 14/100
385047/385047 [==============================] - 69s 178us/step - loss: 8270707.8302
Epoch 15/100
385047/385047 [==============================] - 61s 159us/step - loss: 8245073.5536
Epoch 16/100
385047/385047 [==============================] - 70s 182us/step - loss: 8222231.6526
Epoch 17/100
385047/385047 [==============================] - 65s 170us/step - loss: 8198869.2567
Epoch 18/100
385047/385047 [==============================] - 70s 182us/step - loss: 8178751.9324
Epoch 19/100
385047/385047 [==============================] - 67s 173us/step - loss: 8158848.8778
Epoch 20/100
385047/385047 [==============================] - 67s 173us/step - loss: 8138214.7674
Epoch 21/100
385047/385047 [==============================] - 66s 171us/step - loss: 8120030.9073
Epoch 22/100
385047/385047 [==============================] - 67s 175us/step - loss: 8106863.9888
Epoch 23/100
385047/385047 [==============================] - 64s 167us/step - loss: 8087775.2962
Epoch 24/100
385047/385047 [==============================] - 65s 170us/step - loss: 8075119.4362
Epoch 25/100
385047/385047 [==============================] - 78s 203us/step - loss: 8058343.7640
Epoch 26/100
385047/385047 [==============================] - 77s 201us/step - loss: 8047527.2217
Epoch 27/100
385047/385047 [==============================] - 75s 196us/step - loss: 8034859.9821
Epoch 28/100
385047/385047 [==============================] - 74s 191us/step - loss: 8021981.7028
Epoch 29/100
385047/385047 [==============================] - 68s 175us/step - loss: 8011424.4710
Epoch 30/100
385047/385047 [==============================] - 66s 173us/step - loss: 8000074.8546
Epoch 31/100
385047/385047 [==============================] - 60s 157us/step - loss: 7994245.3028
Epoch 32/100
385047/385047 [==============================] - 59s 153us/step - loss: 7980384.1813
Epoch 33/100
385047/385047 [==============================] - 59s 153us/step - loss: 7971438.0926
Epoch 34/100
385047/385047 [==============================] - 59s 154us/step - loss: 7965286.1761
Epoch 35/100
385047/385047 [==============================] - 61s 157us/step - loss: 7956341.2251
Epoch 36/100
385047/385047 [==============================] - 59s 153us/step - loss: 7946707.8601
Epoch 37/100
385047/385047 [==============================] - 59s 153us/step - loss: 7941153.7834
Epoch 38/100
385047/385047 [==============================] - 59s 154us/step - loss: 7931923.8665
Epoch 39/100
385047/385047 [==============================] - 59s 153us/step - loss: 7926248.6118
Epoch 40/100
385047/385047 [==============================] - 59s 153us/step - loss: 7915547.0953
Epoch 41/100
385047/385047 [==============================] - 59s 154us/step - loss: 7911123.4695
Epoch 42/100
385047/385047 [==============================] - 59s 154us/step - loss: 7904942.0706
Epoch 43/100
385047/385047 [==============================] - 59s 153us/step - loss: 7898276.9196
Epoch 44/100
385047/385047 [==============================] - 59s 154us/step - loss: 7890946.8810
Epoch 45/100
385047/385047 [==============================] - 59s 154us/step - loss: 7886695.3116
Epoch 46/100
385047/385047 [==============================] - 59s 152us/step - loss: 7876766.7219
Epoch 47/100
385047/385047 [==============================] - 59s 153us/step - loss: 7872469.8622
Epoch 48/100
385047/385047 [==============================] - 59s 153us/step - loss: 7865137.6087
Epoch 49/100
385047/385047 [==============================] - 59s 153us/step - loss: 7860418.7022
Epoch 50/100
385047/385047 [==============================] - 50s 130us/step - loss: 7856831.6957
Epoch 51/100
385047/385047 [==============================] - 43s 112us/step - loss: 7853695.68680s - loss: 7854843.
Epoch 52/100
385047/385047 [==============================] - 47s 121us/step - loss: 7846508.0648
Epoch 53/100
385047/385047 [==============================] - 49s 126us/step - loss: 7841908.3179
Epoch 54/100
385047/385047 [==============================] - 53s 137us/step - loss: 7835256.9067
Epoch 55/100
385047/385047 [==============================] - 50s 129us/step - loss: 7830032.8404
Epoch 56/100
385047/385047 [==============================] - 48s 123us/step - loss: 7825961.7229
Epoch 57/100
385047/385047 [==============================] - 47s 122us/step - loss: 7821303.5854
Epoch 58/100
385047/385047 [==============================] - 46s 120us/step - loss: 7816417.3015
Epoch 59/100
385047/385047 [==============================] - 59s 153us/step - loss: 7812268.3260
Epoch 60/100
385047/385047 [==============================] - 59s 154us/step - loss: 7808592.5953
Epoch 61/100
385047/385047 [==============================] - 64s 167us/step - loss: 7803232.9992
Epoch 62/100
385047/385047 [==============================] - 61s 157us/step - loss: 7798483.5888
Epoch 63/100
385047/385047 [==============================] - 49s 128us/step - loss: 7797508.9915
Epoch 64/100
385047/385047 [==============================] - 46s 119us/step - loss: 7794900.66801s - loss:
Epoch 65/100
385047/385047 [==============================] - 45s 117us/step - loss: 7784358.10010s - loss: 778
Epoch 66/100
385047/385047 [==============================] - 45s 118us/step - loss: 7785035.5075
Epoch 67/100
385047/385047 [==============================] - 45s 116us/step - loss: 7775535.23370s - loss: 77
Epoch 68/100
385047/385047 [==============================] - 47s 121us/step - loss: 7775566.5442
Epoch 69/100
385047/385047 [==============================] - 51s 132us/step - loss: 7771228.4479
Epoch 70/100
385047/385047 [==============================] - 60s 157us/step - loss: 7766286.7237
Epoch 71/100
385047/385047 [==============================] - 52s 136us/step - loss: 7766260.4340
Epoch 72/100
385047/385047 [==============================] - 58s 152us/step - loss: 7763058.4526
Epoch 73/100
385047/385047 [==============================] - 54s 141us/step - loss: 7760574.2786
Epoch 74/100
385047/385047 [==============================] - 54s 140us/step - loss: 7754573.2078
Epoch 75/100
385047/385047 [==============================] - 56s 144us/step - loss: 7752523.8196
Epoch 76/100
385047/385047 [==============================] - 59s 153us/step - loss: 7750885.1532
Epoch 77/100
385047/385047 [==============================] - 51s 132us/step - loss: 7746698.4288
Epoch 78/100
385047/385047 [==============================] - 53s 137us/step - loss: 7743176.1176
Epoch 79/100
385047/385047 [==============================] - 54s 141us/step - loss: 7743172.1777
Epoch 80/100
385047/385047 [==============================] - 46s 119us/step - loss: 7736938.4002
Epoch 81/100
385047/385047 [==============================] - 51s 133us/step - loss: 7738074.2759
Epoch 82/100
385047/385047 [==============================] - 53s 138us/step - loss: 7731946.3301
Epoch 83/100
385047/385047 [==============================] - 47s 123us/step - loss: 7730323.8253
Epoch 84/100
385047/385047 [==============================] - 46s 119us/step - loss: 7730016.4987
Epoch 85/100
385047/385047 [==============================] - 49s 128us/step - loss: 7724545.0246
Epoch 86/100
385047/385047 [==============================] - 48s 124us/step - loss: 7725058.2113
Epoch 87/100
385047/385047 [==============================] - 49s 126us/step - loss: 7721998.7318
Epoch 88/100
385047/385047 [==============================] - 49s 127us/step - loss: 7723250.3983
Epoch 89/100
385047/385047 [==============================] - 52s 134us/step - loss: 7718472.3983
Epoch 90/100
385047/385047 [==============================] - 51s 133us/step - loss: 7716032.0600
Epoch 91/100
385047/385047 [==============================] - 50s 129us/step - loss: 7711345.6469
Epoch 92/100
385047/385047 [==============================] - 48s 124us/step - loss: 7712922.1998
Epoch 93/100
385047/385047 [==============================] - 49s 127us/step - loss: 7709523.9246
Epoch 94/100
385047/385047 [==============================] - 47s 123us/step - loss: 7707999.8092
Epoch 95/100
385047/385047 [==============================] - 50s 131us/step - loss: 7706552.6237
Epoch 96/100
385047/385047 [==============================] - 47s 123us/step - loss: 7702325.8142
Epoch 97/100
385047/385047 [==============================] - 49s 127us/step - loss: 7699776.55160s - loss: 76991
Epoch 98/100
385047/385047 [==============================] - 50s 130us/step - loss: 7700891.3842
Epoch 99/100
385047/385047 [==============================] - 55s 142us/step - loss: 7695707.4561
Epoch 100/100
385047/385047 [==============================] - 45s 117us/step - loss: 7696214.8547

In [14]:
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)

print(np.sqrt(mean_squared_error(y_test,y_pred)))

2894.100727632681